# grimms fairy tales selector
s = '''THE GOLDEN BIRD
HANS IN LUCK
JORINDA AND JORINDEL
THE TRAVELLING MUSICIANS
OLD SULTAN
THE STRAW, THE COAL, AND THE BEAN
BRIAR ROSE
THE DOG AND THE SPARROW
THE TWELVE DANCING PRINCESSES
THE FISHERMAN AND HIS WIFE
THE WILLOW-WREN AND THE BEAR
THE FROG-PRINCE
CAT AND MOUSE IN PARTNERSHIP
THE GOOSE-GIRL
THE ADVENTURES OF CHANTICLEER AND PARTLET
RAPUNZEL
FUNDEVOGEL
THE VALIANT LITTLE TAILOR
HANSEL AND GRETEL
THE MOUSE, THE BIRD, AND THE SAUSAGE
MOTHER HOLLE
LITTLE RED-CAP [LITTLE RED RIDING HOOD]
THE ROBBER BRIDEGROOM
TOM THUMB
RUMPELSTILTSKIN
CLEVER GRETEL
THE OLD MAN AND HIS GRANDSON
THE LITTLE PEASANT
FREDERICK AND CATHERINE
SWEETHEART ROLAND
SNOWDROP
THE PINK
CLEVER ELSIE
THE MISER IN THE BUSH
ASHPUTTEL
THE WHITE SNAKE
THE WOLF AND THE SEVEN LITTLE KIDS
THE QUEEN BEE
THE ELVES AND THE SHOEMAKER
THE JUNIPER-TREE
THE TURNIP
CLEVER HANS
THE THREE LANGUAGES
THE FOX AND THE CAT
THE FOUR CLEVER BROTHERS
LILY AND THE LION
THE FOX AND THE HORSE
THE BLUE LIGHT
THE RAVEN
THE GOLDEN GOOSE
THE WATER OF LIFE
THE TWELVE HUNTSMEN
THE KING OF THE GOLDEN MOUNTAIN
DOCTOR KNOWALL
THE SEVEN RAVENS
THE WEDDING OF MRS FOX
THE SALAD
THE STORY OF THE YOUTH WHO WENT FORTH TO LEARN WHAT FEAR WAS
KING GRISLY-BEARD
IRON HANS
CAT-SKIN
SNOW-WHITE AND ROSE-RED'''

from random import choice
li = s.split('\n')
print(choice(li))